[features]
seeds = false
skip-lint = false
[programs.localnet]
crowd_fund = "HwP3YY71PLysJzKzbpYTk1BzNxfg9PNQ8ZZQJzPWAYFs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/geobrodas/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
